import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { navigation } from '@/lib/content';
import { Workspace } from '@/components/workspace';
import { Icon } from '@/components/icon';
const sections = ['about','expertise','projects','workspace','library','contacts'];
export function generateStaticParams() { return sections.map(section => ({section})); }
export async function generateMetadata({ params }: { params: Promise<{section: string}> }): Promise<Metadata> { const {section} = await params; return { title: navigation.find(n => n.href === `/${section}`)?.label || 'Страница не найдена' }; }
const expertise = [ ['layers','Тонкоплёночные покрытия','Процессы PVD, CVD и PECVD. Связь параметров осаждения, структуры и свойств покрытий.'], ['box','Вакуумные системы','Архитектура установок, откачка, газоподача и требования к технологическому оборудованию.'], ['flask','Исследование материалов','Планирование экспериментов, анализ характеристик поверхности и интерпретация результатов.'], ['sliders','Разработка техпроцессов','От постановки задачи и маршрутной карты до контроля качества и воспроизводимости.'], ['chart','Инженерная экономика','Структура затрат, производительность, эксплуатационные расходы и оценка эффективности.'], ['sparkles','AI в инженерной работе','Поддержка поиска литературы, подготовки документов и систематизации инженерных знаний.'] ];
export default async function SectionPage({params}: {params: Promise<{section:string}>}) { const {section} = await params; if (!sections.includes(section)) notFound();
 const title = navigation.find(n => n.href === `/${section}`)!.label;
 const subtitles: Record<string,string> = { about:'Инженерный подход к задачам на пересечении науки, технологий и искусственного интеллекта.', expertise:'От физики плазмы и свойств материалов — к воспроизводимым технологическим процессам.', projects:'Пространство для исследовательских и инженерных разработок.', workspace:'Шесть инструментов для исследований, разработки процессов и инженерных решений.', library:'Короткие справочные материалы для работы с вакуумно-плазменными технологиями.', contacts:'Обсудить исследование, инженерную задачу или развитие платформы.' };
 return <div className="page inner-page"><div className="page-intro"><div className="eyebrow">PLASMATECH AI / {String(sections.indexOf(section)+1).padStart(2,'0')}</div><h1>{title}</h1><p>{subtitles[section]}</p></div>
 {section === 'workspace' && <><div className="notice"><Icon name="sparkles"/><span><strong>Демонстрационный режим</strong> — попробуйте сценарии работы. Все результаты подготовлены заранее.</span></div><Workspace/></>}
 {section === 'about' && <div className="about-layout"><div className="about-monogram"><Icon name="atom" size={100}/><span>PLASMATECH AI</span><small>SCIENCE × ENGINEERING</small></div><div className="prose"><span className="eyebrow">ОБ АВТОРЕ И ПЛАТФОРМЕ</span><h2>Технологии начинаются<br/>с правильных вопросов.</h2><p>PlasmaTech AI — пространство для системной работы с вакуумно-плазменными технологиями: от изучения научной литературы до подготовки технологической документации.</p><p>Платформа объединяет инженерные инструменты, направления исследований и базу знаний. Её задача — сделать путь от научной идеи к практическому решению понятнее.</p><div className="notice">Личная биография, образование и профессиональный опыт автора будут добавлены после заполнения профиля.</div><Link href="/expertise" className="button primary">Направления экспертизы <Icon name="right" size={18}/></Link></div></div>}
 {section === 'expertise' && <div className="content-grid">{expertise.map(([icon,name,description], i) => <article className="content-card" key={name}><div className="content-card-top"><Icon name={icon} size={28}/><span>0{i+1}</span></div><h2>{name}</h2><p>{description}</p></article>)}</div>}
 {section === 'projects' && <><div className="notice"><Icon name="folder"/><span>Концепции для демонстрации структуры портфолио. Реальные проекты и результаты пока не опубликованы.</span></div><div className="project-grid">{[['PVD / МАТЕРИАЛЫ','Функциональные тонкоплёночные покрытия','Исследование связи режимов магнетронного распыления и свойств покрытий.','layers'],['ВАКУУМ / ИНЖЕНЕРИЯ','Вакуумно-плазменный комплекс','Концепция оборудования для разработки и отработки процессов обработки поверхности.','box'],['AI / ИССЛЕДОВАНИЯ','Цифровое рабочее пространство','Инструменты поддержки научной и инженерной работы в единой среде.','sparkles']].map(([tag,name,desc,icon],i) => <article className="project-card" key={name}><div className={`project-art art-${i}`}><Icon name={icon} size={76}/><span>CONCEPT / 0{i+1}</span></div><div className="project-copy"><span className="eyebrow">{tag}</span><h2>{name}</h2><p>{desc}</p><span className="status-label">Концепция</span></div></article>)}</div></>}
 {section === 'library' && <div className="library-list">{[['01','PVD: физическое осаждение из паровой фазы','ТЕХНОЛОГИИ','PVD объединяет методы переноса материала из источника на подложку в вакууме. К ним относятся испарение и распыление. При выборе процесса учитывают материал, геометрию деталей, температуру подложки и требования к покрытию.'],['02','CVD и PECVD: роль плазмы','ПРОЦЕССЫ','При CVD покрытие образуется в результате химических реакций газообразных прекурсоров. PECVD использует плазму для активации реакций. Конкретные режимы зависят от химии процесса и оборудования.'],['03','Что учитывать при выборе вакуумной системы','ОБОРУДОВАНИЕ','Исходные требования включают рабочее и предельное давление, газовую нагрузку, объём камеры и допустимое время откачки. Важно учитывать проводимость вакуумных магистралей и совместимость насоса с рабочими газами.'],['04','Воспроизводимость инженерного эксперимента','МЕТОДОЛОГИЯ','Фиксируйте подготовку образцов, калибровку приборов, последовательность операций и условия измерений. Отделяйте измеренные величины от интерпретаций и обязательно указывайте неопределённость измерений.']].map(([num,title,tag,text]) => <details key={num}><summary><span className="library-number">{num}</span><span><span className="eyebrow">{tag} · СПРАВОЧНАЯ ЗАМЕТКА</span><h2>{title}</h2></span><Icon name="chevron"/></summary><p>{text}</p></details>)}</div>}
 {section === 'contacts' && <div className="contact-panel"><span className="tool-icon"><Icon name="mail" size={30}/></span><h2>Начнём с вашей задачи</h2><p>Научное сотрудничество, разработка технологических процессов, подбор оборудования или предложения по развитию PlasmaTech AI.</p><div className="notice">Контактные данные автора пока не опубликованы. Канал связи появится после настройки профиля.</div><Link href="/workspace" className="button primary">Познакомиться с инструментами <Icon name="right" size={18}/></Link></div>}
 </div>; }
