'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { getWorkspaceModuleHref } from '@/modules/workspace/registry';
import { tools, type Tool } from '@/lib/content';
import { demoProvider, type WorkspaceResult } from '@/lib/demo-provider';
import { Icon } from './icon';
export function Workspace({ compact = false }: { compact?: boolean }) {
 const router = useRouter();
 const [filter, setFilter] = useState('Все инструменты'); const [active, setActive] = useState<Tool | null>(null); const [input, setInput] = useState(''); const [result, setResult] = useState<WorkspaceResult | null>(null); const [busy, setBusy] = useState(false); const dialog = useRef<HTMLDialogElement>(null);
 function launch(tool: Tool) { if (tool.id === 'scifinder') { router.push(getWorkspaceModuleHref(tool.id)); return; } setActive(tool); setInput(''); setResult(null); dialog.current?.showModal(); }
 async function submit(event: React.FormEvent) { event.preventDefault(); if (!active || !input.trim()) return; setBusy(true); try { setResult(await demoProvider.run(active, input)); } finally { setBusy(false); } }
 return <><div className="workspace-toolbar"><div className="filters" aria-label="Категории инструментов">{['Все инструменты', 'Исследования', 'Технологии', 'Оборудование', 'Расчеты'].map(f => <button key={f} className={filter === f ? 'selected' : ''} onClick={() => setFilter(f)} aria-pressed={filter === f}>{f}</button>)}</div>{!compact && <span className="muted small">{tools.filter(t => filter === 'Все инструменты' || t.category === filter).length} инструментов</span>}</div>
 <div className="tool-grid">{tools.filter(t => filter === 'Все инструменты' || t.category === filter).map((tool, i) => <button className="tool-card" key={tool.id} onClick={() => launch(tool)}><div className="tool-top"><span className={`tool-icon color-${i % 3}`}><Icon name={tool.icon} size={23}/></span><span className="card-demo">{tool.id === 'scifinder' ? 'Crossref' : 'Демо'}</span></div><h3>{tool.name}</h3><p>{tool.description}</p><div className="tool-bottom"><span className="tags">{tool.tags.map(t => <span key={t}>{t}</span>)}</span><span className="tool-arrow"><Icon name="arrow" size={19}/></span></div></button>)}</div>
 <dialog ref={dialog} aria-labelledby="tool-title" className="tool-dialog" onClick={e => { if (e.target === e.currentTarget) dialog.current?.close(); }}><div className="dialog-heading"><span className="eyebrow">AI WORKSPACE / DEMO</span><button className="icon-button" onClick={() => dialog.current?.close()} aria-label="Закрыть инструмент"><Icon name="close"/></button></div><h2 id="tool-title">{active?.name}</h2>{active && <Link className="text-link mb-4" href={getWorkspaceModuleHref(active.id)} onClick={() => dialog.current?.close()}>Открыть страницу модуля <Icon name="arrow" size={17}/></Link>}<p className="muted">Демонстрационный инструмент. Запрос не отправляется на сервер; результат — заранее подготовленный пример.</p><form onSubmit={submit}><label htmlFor="task">Ваша задача</label><textarea id="task" required maxLength={4000} value={input} onChange={e => { setInput(e.target.value); setResult(null); }} placeholder={active?.placeholder} rows={4}/><button className="button primary" disabled={busy || !input.trim()}>{busy ? 'Подготовка…' : 'Показать пример'}<Icon name="sparkles" size={17}/></button></form>{result && <section className="demo-result" aria-live="polite"><h3>{result.title}</h3><ul>{result.items.map(item => <li key={item}>{item}</li>)}</ul><p>{result.notice}</p></section>}</dialog></>;
}
